# Generated by Django 5.1 on 2024-08-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='articuloWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('contenido', models.TextField(max_length=1024)),
                ('temaRelacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiApp.temawiki')),
            ],
        ),
    ]
