# Generated by Django 5.1 on 2024-08-24 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulowiki',
            name='temaRelacionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='wikiApp.temawiki'),
        ),
        migrations.AlterField(
            model_name='temawiki',
            name='descripcion',
            field=models.TextField(max_length=512),
        ),
    ]
